default_platform :ios

desc "Build the app"
lane :build do
    unless ENV["BUILD_NUMBER"] && !ENV["BUILD_NUMBER"].empty?
        UI.user_error!("A BUILD_NUMBER must be provided.")
        exit(1)
    end

    unless ENV["VERSION_NUMBER"] && !ENV["VERSION_NUMBER"].empty?
        UI.user_error!("A VERSION_NUMBER must be provided.")
        exit(1)
    end

    increment_build_number(build_number: ENV["BUILD_NUMBER"])
    increment_version_number(version_number: ENV["VERSION_NUMBER"])

    app_store_connect
    setup_ci
    get_certs
    update_code_signing_settings
    clear_derived_data
    cocoapods(
        clean_install: true
    )
    build_app(
        clean: true,
        silent: false,
        output_name: "macro-deck-client.ipa"
    )
end

desc "Get certs for the app"
lane :get_certs do
    match(
        type: "development",
        readonly: true
    )
    match(
        type: "appstore",
        readonly: true
    )
end

desc "Configure AppStoreConnect api"
private_lane :app_store_connect do
    app_store_connect_api_key(
        key_id: ENV["KEY_ID"],
        issuer_id: ENV["ISSUER_ID"],
        key_content: ENV["KEY_CONTENT"]
    )
end

desc "Deploy a new version of the app to TestFlight"
lane :release do
    app_store_connect
    upload_to_testflight(
        distribute_external: true,
        groups: [
            "Macro Deck Client testing"
        ],
        changelog: ENV["CHANGELOG"]
    )
end
