name: Deploy Develop

on:
  workflow_dispatch:
  push:
    branches: [ "develop" ]

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    name: Build

  deploy:
    name: Deploy Docker image
    environment: staging
    needs: [ ci ]
    runs-on: ubuntu-latest
    steps:
      - name: Updating the image on the server
        uses: Macro-Deck-App/Actions/deploy@main
        with:
          host: ${{ secrets.TEST_DEPLOY_HOST }}
          user: ${{ secrets.TEST_DEPLOY_USER }}
          key: ${{ secrets.TEST_DEPLOY_KEY }}
          known-hosts: ${{ secrets.TEST_DEPLOY_KNOWN_HOSTS }}
          sha: ${{ github.sha }}
          service: macro-deck-web-client
