name: Deploy Develop

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    name: Build

  deploy:
    name: Deploy Docker image
    environment: production
    needs: [ ci ]
    runs-on: ubuntu-latest
    steps:
      - name: Updating the image on the server
        uses: Macro-Deck-App/Actions/deploy@main
        with:
          host: ${{ secrets.LIVE_DEPLOY_HOST }}
          user: ${{ secrets.LIVE_DEPLOY_USER }}
          key: ${{ secrets.LIVE_DEPLOY_KEY }}
          known-hosts: ${{ secrets.LIVE_DEPLOY_KNOWN_HOSTS }}
          sha: ${{ github.sha }}
          service: macro-deck-web-client
