name: Deploy Develop

on:
  release:
    types: [published]

jobs:
  build-android:
    uses: ./.github/workflows/ci-build-android.yml
    name: Build Android App
    secrets: inherit
    with:
      version: ${{ github.event.release.name }}
  build-ios:
    uses: ./.github/workflows/ci-build-ios.yml
    name: Build iOS App
    secrets: inherit
    with:
      version: ${{ github.event.release.name }}
